apiVersion: v1
kind: Service
metadata:
  name: diaptcher-service
  labels:
    app: diaptcher-service
spec:
  type: ClusterIP
  selector:
    app: diaptcher-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9003